export OS_USERNAME=xxxxx
export OS_PASSWORD=xxxxx
export OS_PROJECT_NAME=xxxxxx
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_DOMAIN_NAME=Default
export OS_AUTH_URL=http://172.23.0.11:5000/v3
export OS_IDENTITY_API_VERSION=3
export OS_VOLUME_API_VERSION=3
export OS_PLACEMENT_API_VERSION=1.17
export PS1="\u@\h($OS_USERNAME):\w# "
#export PS1="\u@\h(\e[32;1m${OS_USERNAME}\e[0m):\w# "
